### ISSUE TITLE
feature request: Quick Settings Tiles for faster toggling vpn

### ISSUE THREAD

**Issue by yaoxinghuo** [dlenski/ics-openconnect#2]
Hi,
Can you please kindly implement this feature, it is very handy! Thank you!
[Orignal Issue](https://github.com/cernekee/ics-openconnect/issues/31)

**Comment by dlenski** [comment]
It's a good idea but I'm… not really an Android developer. This is way over my head for the time being. 

Pull requests welcome. ¯\\\_(ツ)\_\/¯

**Comment by yaoxinghuo** [comment]
@dlenski I am an Android developer, but I'm not familiar with linux/C related programing...
Still, I will try to create a vm with linux environment, if everything goes fine, I will implement this and make pull requests. Thanks!
